#include <stdio.h> // BIBLIOTECA IMPORTADA PARA USAR A FUNÇAO printf e scanf

/*

UM PROGRAMA QUE SOMA DOIS NUMEROS DIGITADOS PELO USUÁRIO DO PROGRAMA E CALCULA SUA SOMA.

OBS 1.: NÃO USEM ACENTOS ou cedilha EM printf, PODE SER USADO EM COMENTARIO
OBS 2.: %d SERVE PARA ARMAZENAR VALORES INTEIROS (NÃO POSSUEM VIRGULA)

*/

int main() { // INICIO DA FUNÇÃO PRINCIPAL INICIDADO POR UMA CHAVE, É ONDE VOCÊ VAI ESCREVER SEU CÓDIGO E O MESMO SERA EXECUTADO
	
	int numero1;    // DECLARO UMA VARIAVEL PARA GUARDAR UM VALOR DO TIPO INTEIRO
	int numero2;    // DECLARO UMA VARIAVEL PARA GUARDAR OUTRO VALOR DO TIPO INTEIRO
	int soma;        //DECLARO UMA VARIAVEL PARA GUARDAR O RESULTADO DA OPERAÇÃO ENVOLVENDO OS VALORES ANTERIORES
	
	printf("DIGITE UM NUMERO: "); // EXIBO UMA MENSAGEM PEDINDO PRO USUARIO DIGITAR UM NUMERO
	scanf("%d", &numero1);      // GUARDO O NÚMERO QUE ELE DIGITOU NA VARIAVEL numero1
	
	
	printf("DIGITE OUTRO NUMERO: ");  // EXIBO OUTRA MENSAGEM PRO USUARIO DIGITAR OUTRO NUMERO
	scanf("%d", &numero2);          // GUARDO NOVAMENTE O NÚMERO QUE ELE DIGITOU, AGORA NA VARIAVEL numero2
	
	
	soma = numero1 + numero2;       // A VARIAVEL soma, VAI FAZER A SOMA DOS VALORES QUE FORAM GUARDADOS NAS VARIÁVEIS numero1 E numero2
	
	
	printf("A soma de %d com %d eh: %d", numero1, numero2, soma); // AQUI EXIBO O RESULTADO DA SOMA
	
	// CADA %d SERÁ SUBSTITUIDO PELO VALOR GUARDADO NAS VARIAVEIS ACIMA.
	

	return 0;  // COMO A FUNÇÃO É DO TIPO INTEIRO, ELA TEM QUE RETORNA ALGO, AQUI RETORNA ZERO, MAS ISSO NÃO TEM INFLUÊNCIA NO NOSSO PROGRAMA
	
} //FIM DA FUNÇÃO PRINCIPAL FECHADO POR CHAVE
